# Generated by Django 4.2 on 2023-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_date_added_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='customer_age',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='customer_licenses',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
